version: "3.8"
services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    networks:
      - flask-api

  flask-api:
    image: iterative/flask-api
    container_name: flask-api
    build:
      context: .
      target: debug
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_RUN_PORT=8000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
      - APP_SETTINGS=config.DevelopmentConfig
      - OPENAI_API_KEY="test"
      - STYTCH_PROJECT_ENV=test
      - STYTCH_PROJECT_ID=project-test-5981764b-bbf0-47f0-80d3-cae8de7c258c
      - NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN=public-token-test-14b26229-48ce-4a71-ba1c-3531f21ea5fa
      - STYTCH_SECRET=secret-test-NddFy9yYTlTli5w6_2TYUDSzQ3ScUiagPRQ=
    depends_on:
      db:
        condition: service_healthy    
    links: 
      - db
    command: >
      sh -c "python3 ./create_db.py &&
             flask run --debug --host=0.0.0.0 --port=8000"
    networks:
      - flask-api
    

networks:
  flask-api:
    name: flask-api